## ET Entrega 1 
# Caso Análisis de Condiciones Climáticas en Australia

* Maura Ruminot
* Paula Romero

In [1]:
# Importación de librerías
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns
from collections import Counter
import warnings
warnings.filterwarnings("ignore")

In [2]:
data = pd.read_csv("australiaEDA.csv")
data.head()

,Unnamed: 0,Date,Location,MinTemp,MaxTemp,Rainfall,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,...,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RISK_MM,RainTomorrow,RainTomorrow_num,RainToday_num
0,0,2008-12-01,Albury,13.4,22.9,0.6,W,44.0,W,WNW,...,1007.1,8.0,8.0,16.9,21.8,0.0,0.0,0,0,0.0
1,1,2008-12-02,Albury,7.4,25.1,0.0,WNW,44.0,NNW,WSW,...,1007.8,8.0,8.0,17.2,24.3,0.0,0.0,0,0,0.0
2,2,2008-12-03,Albury,12.9,25.7,0.0,WSW,46.0,W,WSW,...,1008.7,8.0,2.0,21.0,23.2,0.0,0.0,0,0,0.0
3,3,2008-12-04,Albury,9.2,28.0,0.0,NE,24.0,SE,E,...,1012.8,8.0,8.0,18.1,26.5,0.0,1.0,0,0,0.0
4,4,2008-12-05,Albury,17.5,32.3,1.0,W,41.0,ENE,NW,...,1006.0,7.0,8.0,17.8,29.7,0.0,0.2,0,0,0.0

In [3]:
print(data['Location'].unique())

['Albury' 'BadgerysCreek' 'Cobar' 'CoffsHarbour' 'Moree' 'Newcastle'
 'NorahHead' 'NorfolkIsland' 'Penrith' 'Richmond' 'Sydney' 'SydneyAirport'
 'WaggaWagga' 'Williamtown' 'Wollongong' 'Canberra' 'Tuggeranong'
 'MountGinini' 'Ballarat' 'Bendigo' 'Sale' 'MelbourneAirport' 'Melbourne'
 'Mildura' 'Nhil' 'Portland' 'Watsonia' 'Dartmoor' 'Brisbane' 'Cairns'
 'GoldCoast' 'Townsville' 'Adelaide' 'MountGambier' 'Nuriootpa' 'Woomera'
 'Albany' 'Witchcliffe' 'PearceRAAF' 'PerthAirport' 'Perth' 'SalmonGums'
 'Walpole' 'Hobart' 'Launceston' 'AliceSprings' 'Darwin' 'Katherine'
 'Uluru']

In [4]:
# transformando en dummies --> one.hot.enconding
data = pd.get_dummies(data, columns=["Location"])
data.head()

,Unnamed: 0,Date,MinTemp,MaxTemp,Rainfall,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,WindSpeed9am,...,Location_Townsville,Location_Tuggeranong,Location_Uluru,Location_WaggaWagga,Location_Walpole,Location_Watsonia,Location_Williamtown,Location_Witchcliffe,Location_Wollongong,Location_Woomera
0,0,2008-12-01,13.4,22.9,0.6,W,44.0,W,WNW,20.0,...,0,0,0,0,0,0,0,0,0,0
1,1,2008-12-02,7.4,25.1,0.0,WNW,44.0,NNW,WSW,4.0,...,0,0,0,0,0,0,0,0,0,0
2,2,2008-12-03,12.9,25.7,0.0,WSW,46.0,W,WSW,19.0,...,0,0,0,0,0,0,0,0,0,0
3,3,2008-12-04,9.2,28.0,0.0,NE,24.0,SE,E,11.0,...,0,0,0,0,0,0,0,0,0,0
4,4,2008-12-05,17.5,32.3,1.0,W,41.0,ENE,NW,7.0,...,0,0,0,0,0,0,0,0,0,0

In [5]:
# Transformar la columna Location en variables dummy
data_dummies = pd.get_dummies(data, columns=['Location'])

# Revisar las primeras filas del DataFrame transformado
print("\nPrimeras filas del DataFrame transformado:")
print(data_dummies.head())

# Verificar las columnas dummy creadas
print("\nColumnas dummy creadas:")
print(data_dummies.columns)

KeyError: "None of [Index(['Location'], dtype='object')] are in the [columns]"